[package]
name = "ip_exporter"
version = "0.1.0"
authors = ["Jamie Ly <jly@ecri.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pnet = "0.26.0"
rocket = "0.4.5"
prometheus = "0.9.0"
lazy_static = "1.4"
